apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: thermometers.d2iq.com
spec:
  group: d2iq.com
  version: v1
  names:
    kind: Thermometer
    plural: thermometers
    shortNames:
      - therm
  scope: Namespaced
  preserveUnknownFields: false
  validation:
      openAPIV3Schema:
        type: object
        description: Thermometer is the Schema for the Thermometer API.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Thermometer Spec defines the desired state of Thermometer
            type: object
            properties:
              unit:
                description: Units in Celcius or Fahrenheit
                type: string
                anyOf: [{"pattern": "^Celcius"}, {"pattern": "^Fahrenheit"}]
            required: ["unit"]
          status:
            description: Thermometer Status defines the possible status states for Thermometer
            type: object
            properties:
              temperature:
                type: number
